### ISSUE TITLE
remove debug dependency

### ISSUE THREAD

**Issue by charleshansen** [joshjung/hash-array#1]
Can you remove the debug dependency in your package.json? 

I am using `trie-search` (btw, I like it much better than many of the other trie libraries). I gave `snyk` a try and it flagged the version of `ms` used by your version of `debug` as insecure due to some regex bug. I don't see any uses of `debug` in your code, so it can't hurt to remove it. I'd rather not install an npm module I am not actually using. If there is a some reason you need `debug`, can you bump the version?

Thanks

**Comment by joshjung** [comment]
Sorry, I just saw this! I'll take a look as soon as I can here.

**Comment by joshjung** [comment]
Sorry this took forever, this is finally fixed! @charleshansen
